apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    project: ecommerce
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: helath
  labels:
    project: ecommerce
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: nothing
  labels:
    project: ecommerce
    environment: production