apiVersion: v1
kind: Pod
metadata:
  name: labels-demo
  labels:
    purpose: testing
    project: roboshop
  Annotations:
    use: "we are building k8-cluster"
spec:
  containers:
  - name: nginx
    image: nginx
