apiVersion: v1
kind: Secret
metadata:
  name: secrets-demo
type: Opaque
data:
  course: YXdz
  project: cm9ib3Nob3A=
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret

spec:
  containers:
  - name: pod-secret
    image: nginx
    envFrom:
    - secretRef:
        name: secrets-demo