# Important: pod name must be unique within a namespace.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-single-pod
spec:
  containers:
    - name: nginx
      image: nginx

# Notes
# Basic single-container pod example.
# IMP: pod name must be unique within a namespace.


# Commands:
#   kubectl get pods
#   kubectl describe pod nginx-single-pod
#   kubectl logs nginx-single-pod
