apiVersion: v1
kind: Pod
metadata: 
  name: env-pod
  labels:
    purpose: env-demo
    env: prod
    project: wipro
    tier: backend
spec:
  containers:
    - name: nginx-env
      image: nginx
      env:
        - name: rds
          value: "password"
