# Important: store only non-sensitive configuration data in ConfigMap.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config

data:
  TRAINER_NAME: "vicky"
  COURSE_NAME: "aws"
  COURSE_HOURS: "100"

# Notes
# ConfigMap containing non-sensitive application settings.
# IMP: store only non-sensitive config in ConfigMap.


# Commands:
#   kubectl get configmap
#   kubectl describe configmap app-config
