apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
type: Opaque
data:
  username: "YWRtaW4="
  password: "dGVzdA=="

---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: secret-pod
# spec:
#   containers:
#     - name: test
#       image: nginx
#       envFrom:
#         - secretRef:
#             name: pod-config