apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    purpose: service-demo
    env: dev
    project: wipro

spec:
  selector:
    env: test
    purpose: pod-service-demo
    project: roboshop

  ports:
    - protocol: TCP
      port: 80          # Service Port
      targetPort: 80    # Container Port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    env: test
    purpose: pod-service-demo
    project: roboshop

spec:
  containers:
    - name: nginx
      image: nginx


# Commands:
#   kubectl get svc
#   kubectl describe svc my-service
#   kubectl get pods
#   kubectl describe pod nginx-service
#   kubectl logs nginx-service
