apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    purpose: service-demo
    env: dev
    project: wipro
spec:
  selector:
    #pod labels
    env: test
    purpose: pod-service-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 #service
      targetPort: 80 #service
      
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  lables:
    env: test
    purpose: pod-service-demo
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
