# Important: Service selector labels must match the target Pod labels.
apiVersion: v1
kind: Service
metadata:
  name: service-np

spec:
  type: NodePort
  selector: #pod lables
    env: test
    purpose: pod-service-np-demo
    project: roboshop

  ports:
    - protocol: TCP
      port: 80          # Service Port
      targetPort: 80    # Container Port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-np-service
  labels:
    env: test
    purpose: pod-service-np-demo
    project: roboshop

spec:
  containers:
    - name: nginx
      image: nginx


# Commands:
#   kubectl get svc
#   kubectl describe svc service-np
#   kubectl get pods
#   kubectl describe pod nginx-np-service
#   kubectl logs nginx-np-service
