apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector: #pod lables
    env: test
    purpose: pod-service-lb-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80          # Service Port
      targetPort: 80    # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb-service
  labels:
    env: test
    purpose: pod-service-lb-demo
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
