# Important: Deployment manages ReplicaSets and pod rollouts automatically.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  labels:
    app: backend
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      project: roboshop
      purpose: deployment-demo
  template:
    metadata:
      labels:
        env: dev
        project: roboshop
        purpose: deployment-demo
    spec:
      containers:
        - name: nginx
          image: nginx


# Commands:
#   kubectl get deployment
#   kubectl describe deployment nginx-dp
