# Important: pod name must be unique within a namespace.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness

spec:
  containers:
  - name: nginx
    image: nginx

    ports:
    - containerPort: 80    # Nginx listens on port 80

    livenessProbe:
      httpGet:
        path: /abc          # Intentionally wrong path for demo
        port: 80

      initialDelaySeconds: 10   # Wait 10 seconds before first health check
      periodSeconds: 5          # Perform health check every 5 seconds ports


# Commands:
#   kubectl get pods
#   kubectl describe pod nginx-liveness
#   kubectl logs nginx-liveness
